### ISSUE TITLE
Running wal breaks everything 

### ISSUE THREAD

**Issue by paanvaannd** [blahsd/snwe#3] opened 2018-05-08 14:10 UTC
It would be great to have theme pywal-generated theme integration in this project similar to supernerd.

I'm aware that this is a new project so it may be a low priority at the moment. I think an issue would be helpful in tracking this feature for myself and others interested in using it if it is in the works.

Is such an integration possible with the electron framework? If it is already set up, is there documentation about how to set it up?

**Comment by blahsd** [comment] 2018-05-08 15:03
Should work now, provided that you have ~/.cache/wal/colors.css - let me know if it actually does. You activate the pywal colorscheme in the preference pane.

**Comment by blahsd** [comment] 2018-05-08 23:06
See latest commit. It's a sort of hackish workaround which creates the pywal symlink if it's not there – since it's creating it by expanding $HOME/.cache/wal/colors.css, I have good hope that it might work on all systems that respect that convention, regardless of where snwe (which was probably the issue before). I'm not very satisfied with this solution, and even if it ends up working (which is a big if) I might come back to this when releasing a packaged version.

A couple things that you could check in order to make sure that this is working as intended.
1. Before running this version for the first time, please make sure that ../snwe/app/css/colors-wal.css is  **not present** .
2. After running the script, everything might load up correctly. If it doesn't, please try closing and reopening. 
3. If something hasn't worked on the first try, please check that: (a) ./snwe/app/css/colors-wal.css **now exists** and that (b) it points to ~/.cache/wal/colors.css correctly.

**Comment by paanvaannd** [comment] 2018-05-09 00:47
Pywal-generated colors now work and the outlined and non-interactive icon/text issue is fixed!

Prior to this commit, though, I was able to select the default colorscheme and choose between the 4 themes. However, though the pywal colorscheme is now working, it does not let me choose the Default colorscheme and I am stuck with the Center theme.

Also, regenerating a pywal colorscheme when snwe is open causes snwe to disappear completely (along with all text/icon objects and all) though Electron is still running.

**Comment by blahsd** [comment] 2018-05-09 13:37
> Pywal-generated colors now work and the outlined and non-interactive icon/text issue is fixed!

Good.

> Prior to this commit, though, I was able to select the default colorscheme and choose between the 4 themes. However, though the pywal colorscheme is now working, it does not let me choose the Default colorscheme and I am stuck with the Center theme.
Can you confirm that this is still the case? I can't reproduce.

> Also, regenerating a pywal colorscheme when snwe is open causes snwe to disappear completely (along with all text/icon objects and all) though Electron is still running.
Can confirm. Will have to work on this.

**Closed** 2018-05-16 22:59 UTC
Labels: bug
